force-app/main/default/objects/Field_setup__c/Field_setup__c.object-meta.xml
<CustomObject>
    <label>Field setup</label>
    <nameField>
        <label>Source Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fscMigration/force-app/main/default/objects/Field_setup__c/fields/Object_setup_name__c.field-meta.xml
<CustomField>
    <fullName>Object_setup_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Object setup name</label>
    <referenceTo>Object_setup__c</referenceTo>
    <relationshipLabel>Field setups</relationshipLabel>
    <relationshipName>Field_setups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_setup__c/Object_setup__c.object-meta.xml
<CustomObject>
    <label>Object setup</label>
    <nameField>
        <label>Source Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fscMigration/force-app/main/default/objects/Object_setup__c/fields/Destination_Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Object_Name__c</fullName>
    <label>Destination Object Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fscMigration/force-app/main/default/objects/Object_setup__c/fields/SalesforceOrg__c.field-meta.xml
<CustomField>
    <fullName>SalesforceOrg__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SalesforceOrg</label>
    <referenceTo>SalesforceOrg__c</referenceTo>
    <relationshipLabel>Object setups</relationshipLabel>
    <relationshipName>Object_setups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesforceOrg__c/SalesforceOrg__c.object-meta.xml
<CustomObject>
    <label>SalesforceOrg</label>
    <nameField>
        <label>SalesforceOrg Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SalesforceOrg</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fscMigration/force-app/main/default/classes/ExportDataController.cls
public class ExportDataController {
    
    @AuraEnabled
    public static List<Object_setup__c> getObjectSetupOptions(Id connectedSalesforceOrgId){
        System.debug('Connected salesforce org id @@@ ' + connectedSalesforceOrgId);
        List<Object_setup__c> objectSetUpLst = new List<Object_setup__c>();
        objectSetUpLst = [SELECT id,Name,Destination_Object_Name__c
                          FROM Object_setup__c
                          WHERE id in (Select Object_setup_name__c from Field_setup__c  where Object_setup_name__r.SalesforceOrg__c =:connectedSalesforceOrgId)];

        return objectSetUpLst;
    }
}