fscMigration/force-app/main/default/objects/Batch_Transaction_Detail__c/Batch_Transaction_Detail__c.object-meta.xml
<CustomObject>
    <label>Batch Transaction Detail</label>
    <nameField>
        <displayFormat>Batch-{0000}</displayFormat>
        <label>Batch Transaction Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Transaction Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fscMigration/force-app/main/default/objects/Batch_Transaction_Detail__c/fields/Batch_Failed__c.field-meta.xml
<CustomField>
    <fullName>Batch_Failed__c</fullName>
    <label>Batch Failed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fscMigration/force-app/main/default/objects/Batch_Transaction_Detail__c/fields/Batch_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Id__c</fullName>
    <label>Batch Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fscMigration/force-app/main/default/objects/Batch_Transaction_Detail__c/fields/Batch_Success__c.field-meta.xml
<CustomField>
    <fullName>Batch_Success__c</fullName>
    <label>Batch Success</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

fscMigration/force-app/main/default/objects/Batch_Transaction_Detail__c/fields/Object_setup_name__c.field-meta.xml
<CustomField>
    <fullName>Object_setup_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Object setup name</label>
    <referenceTo>Object_setup__c</referenceTo>
    <relationshipLabel>Batch Transaction Details</relationshipLabel>
    <relationshipName>Batch_Transaction_Details</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Transaction_Detail__c/fields/Total_Batch__c.field-meta.xml
<CustomField>
    <fullName>Total_Batch__c</fullName>
    <label>Total Batch</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Field_setup__c/Field_setup__c.object-meta.xml
<CustomObject>
    <label>Field setup</label>
    <nameField>
        <label>Source Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Field setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Field_setup__c/fields/Destination_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Field_Api_Name__c</fullName>
    <label>Destination Field Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

fscMigration/force-app/main/default/objects/Field_setup__c/fields/Object_setup_name__c.field-meta.xml
<CustomField>
    <fullName>Object_setup_name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Object setup name</label>
    <referenceTo>Object_setup__c</referenceTo>
    <relationshipLabel>Field setups</relationshipLabel>
    <relationshipName>Field_setups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

fscMigration/force-app/main/default/objects/Field_setup__c/fields/Souce_Field_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Souce_Field_Api_Name__c</fullName>
    <externalId>true</externalId>
    <label>Souce Field Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Object_setup__c/Object_setup__c.object-meta.xml
<CustomObject>
    <label>Object setup</label>
    <nameField>
        <label>Source Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

fscMigration/force-app/main/default/objects/Object_setup__c/fields/Destination_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Destination_Object_Api_Name__c</fullName>
    <label>Destination Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

fscMigration/force-app/main/default/objects/Object_setup__c/fields/Souce_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Souce_Object_Api_Name__c</fullName>
    <externalId>true</externalId>
    <label>Souce Object Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchMigrateObject.cls
global with sharing class BatchMigrateObject implements Database.Batchable<sObject> {
    String objectsetupname;
    String query;
    String authId;
    Map<String,String> fieldobjectmap;
    
    global BatchMigrateObject(String authId,String objectsetupname) {
        this.objectsetupname=objectsetupname;
        this.authId=authId;
        String sourcefieldName='Id,';

        Object_setup__c objectName=[SELECT Destination_Object_Api_Name__c,Souce_Object_Api_Name__c FROM Object_setup__c WHERE Id =:objectsetupname LIMIT 1];
        List<Field_setup__c> fieldName=[SELECT Destination_Field_Api_Name__c,Souce_Field_Api_Name__c FROM Field_setup__c WHERE Object_setup_name__c=:objectsetupname ];
        Map<String,String> fieldobjectmap=new Map<String,String>();
        
        if(objectName.Souce_Object_Api_Name__c!=objectName.Destination_Object_Api_Name__c){
           fieldobjectmap.put(objectName.Souce_Object_Api_Name__c,objectName.Destination_Object_Api_Name__c);
        }
       
        for(Field_setup__c fn:fieldName){
           sourcefieldName=sourcefieldName+fn.Souce_Field_Api_Name__c+',';
           if(fn.Destination_Field_Api_Name__c!=fn.Souce_Field_Api_Name__c){
               fieldobjectmap.put(fn.Souce_Field_Api_Name__c,fn.Destination_Field_Api_Name__c);
           }
         }
         
        sourcefieldName=sourcefieldName.removeEnd(',');
        this.query='SELECT'+sourcefieldName+'FROM'+ objectName.Souce_Object_Api_Name__c;

    }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<sObject> sobjList){
      MigrateObject.migrateObjectDataInFSC(sobjList,authId,objectsetupname,fieldobjectmap);
   }

   global void finish(Database.BatchableContext BC){
      AsyncApexJob a = [Select a.TotalJobItems, a.NumberOfErrors,a.JobItemsProcessed From AsyncApexJob a WHERE id = :BC.getJobId()];
      Batch_Transaction_Detail__c newBatch=new Batch_Transaction_Detail__c();
      newBatch.Batch_Failed__c= a.NumberOfErrors;
      newBatch.Batch_Id__c=BC.getJobId();
      newBatch.Batch_Success__c=a.JobItemsProcessed;
      newBatch.Object_setup_name__c=objectsetupname;
      newBatch.Total_Batch__c=a.TotalJobItems;

      insert newBatch;

   }

}